[package]
name = "lumina-pdf"
version = "1.1.0"
description = "A fast PDF reader"
authors = ["kuozher"]
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pdfium-render = "0.8"
image = "0.25"
base64 = "0.22"
rfd = "0.14" # Native file dialog
anyhow = "1.0"
url = "2.5.8"
lopdf = "0.34"
printers = "2"
windows = { version = "0.58", features = [
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Printing",
    "Win32_Devices",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_FileSystem",
] }
windows-sys = { version = "0.59", features = [
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Printing",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.dev.package."*"]
opt-level = 3
